### ISSUE TITLE
Inline Inspect?

### ISSUE THREAD

**Issue by Sinaloit** [wildstarnasa/GeminiLogging#1]
The most common problem with people implementing GeminiLogging seems to be forgetting to include inspect.lua in their toc.xml. To help resolve this we could inline inspect into GeminiLogging it could still be a package though as you can define more than 1 package per lua file if you want. What do you think @draftomatic

**Comment by Togglebutton** [comment]
Could be a licensing thing. Otherwise he'd probably have done it.

**Comment by LSAnthony** [comment]
I tried this a long time ago and couldn't get the inspect code to work well in the same file. However I think that was before inspect got a major rework, so feel free to try it again. I definitely agree that it would be a better setup.

**Comment by Sinaloit** [comment]
44ea74106d7fdf139d3c9aae445a6f4a3d9a92f7 Resolves this issue.  Inspect is now inlined.
Also provided partial defaults, can specify `:GetLogger({level="DEBUG"})` and have the pattern and appender be the default
